name: Lint workflows

permissions:
  contents: read # Use 'read' unless you specifically need 'write'

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main # Replace with the correct branch name if different

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint GitHub Actions workflows
        uses: cschleiden/actions-linter@v1
        with:
          workflows: '[".github/workflows/*.yaml"]'
